alias firefox="flatpak run org.mozilla.firefox"
alias jar="/usr/java/jdk-17.0.5/bin/java -jar"
alias adb="/home/frazer/platform-tools/adb"
alias guiscrcpy="flatpak run in.srev.guiscrcpy"
alias prism="flatpak run org.prismlauncher.PrismLauncher"
alias nf="neofetch"
alias flatseal="flatpak run com.github.tchx84.Flatseal"
alias blender="flatpak run org.blender.blender"
alias arch="lxc exec arch -- bash"
alias cmd="wine cmd"
alias explorer="wine explorer"
alias jd-gui="java -jar /opt/jd-gui/jd-gui.jar"
alias ddlc="/home/frazer/ddlc/DDLC.sh"
alias renpy="/home/frazer/renpy-6.99.12.4-sdk/renpy.sh"
alias vim="nvim"
alias protontricks='flatpak run com.github.Matoking.protontricks'
alias protontricks-launch='flatpak run --command=protontricks-launch com.github.Matoking.protontricks'
