# =================================================================================================
# Here is global, all global key can't conflicts with other hotkeys
confirm = ['enter', '']
quit = ['ctrl+c', '']
# movement
list_up = ['k', '']
list_down = ['j', '']
# file panel control
close_file_panel = ['q', '']
create_new_file_panel = ['n', '']
next_file_panel = ['tab', '']
previous_file_panel = ['shift+tab', '']
toggle_file_preview_panel = ['f', '']
# change focus
focus_on_process_bar = ['ctrl+p', '']
focus_on_sidebar = ['ctrl+s', '']
focus_on_metadata = ['ctrl+m', '']
# create file/directory and rename 
file_panel_item_create = ['a', '']
file_panel_item_rename = ['r', '']
# file operate
copy_items = ['y', '']
paste_items = ['p', '']
cut_items = ['x', '']
delete_items = ['d', '']
# compress and extract
extract_file = ['ctrl+e', '']
compress_file = ['ctrl+a', '']
# editor
open_file_with_editor = ['e', '']
open_current_directory_with_editor = ['E', '']
# else
pinned_directory = ['P', '']
toggle_dot_file = ['.', '']
change_panel_mode = ['m', '']
open_help_menu = ['?', '']
open_command_line = [':', '']
# =================================================================================================
# Here is typing hotkey can conflict with all hotkeys
confirm_typing = ['enter', '']
cancel_typing = ['esc', '']
# =================================================================================================
# Here is normal mode hotkey you can conflicts with other mode (can't conflicts with global hotkey)
parent_directory = ['-', '']
search_bar = ['/', '']
# =================================================================================================
# Here is select mode hotkey you can conflicts with other mode (can't conflicts with global hotkey)
file_panel_select_mode_items_select_down = ['J', '']
file_panel_select_mode_items_select_up = ['K', '']
file_panel_select_all_items = ['A', '']
