[[themes]]
name = "pywal"
[themes.palette]
background = "#0f1c25"
foreground = "#c3c6c8"
black = "#0f1c25"
red = "#205e90"
green = "#3e7477"
yellow = "#096999"
blue = "#1e7e9f"
magenta = "#46879c"
cyan = "#4e96a5"
white = "#92989c"
bright_black = "#5f6b74"
bright_red = "#2B7EC0"
bright_green = "#539B9F"
bright_yellow = "#0D8CCD"
bright_blue = "#29A8D5"
bright_magenta = "#5EB4D1"
bright_cyan = "#68C8DD"
bright_white = "#c3c6c8"
    
